pimanager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'device_status'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.device_list, name='index'),
    path('all', views.device_list_all, name='index'),
    path('device_status/', views.device_list, name='status'),
    path('device_status/report', views.report, name='report'),
    path('report', views.report, name='report'),
    path('devices', views.device_list, name='devices'),
    path('actions/<str:mac>', views.actions_json, name='actions'),
                  path('actions/<str:serial>/pending', views.action_list, name='actions_pending'),
    path('actions', views.action_list, name='action_list'),
    path('action_report', views.action_report, name='action_report'),
    path('power_cycle/<str:device>', views.power_cycle, name='power_cycle_device'),
    path('setup', views.client_setup, name='setup'),
    path('upgrade', views.client_upgrade, name='client_upgrade'),
    path('player', views.player_setup, name='setup_player'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pimanager/templates/pimanager/actions.html
{% extends 'pimanager/base.html' %}

{% block content %}
    {% if actions %}
	<table border="1">
	<tr>
		<th>Enhet</th>
		<th>Kommando</th>
		<th>Lagt til</th>
		<th>Kjørt</th>
		<th>Returkode</th>
		<th>Utdata</th>
	</tr>
	{% for action in actions %}
        <tr>
            <td>{{ action.device }}</td>
            <td>{{ action.command }}</td>
        <td>{{ action.added }}</td>
        <td>{{ action.executed }}</td>
        <td>{{ action.return_code }}</td>
        <td><span style="font-family: monospace;">{{ action.output|linebreaksbr }}</span></td>
        </tr>
    {% endfor %}
    </table>
    {% endif %}
{% endblock %}

pimanager/templates/pimanager/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    {% if title %}
        <title>Pimanager - {{ title }}</title>
    {% else %}
        <title>Pimanager</title>
    {% endif %}
    <link href="{% static "pimanager/pimanager.css" %}" rel="stylesheet" type="text/css">
</head>

<body>
<h1>Pimanager {{ version }}</h1>
<hr>
{% block content %} {% endblock %}
</body>
</html>

pimanager/templates/pimanager/devices.html
{% extends 'pimanager/base.html' %}

{% block content %}
    {% if devices %}
        <table border="1">
            <tr>
                <th>Nummer</th>
                <th>Serienr</th>
                <th>Modell</th>
                <th>IP</th>
                <th>Port</th>
                <th>PoE</th>
                <th>Navn</th>
                <th>Beskrivelse</th>
                <th>Sist aktiv</th>
                <th>Oppetid</th>
                <th>Siste status</th>
                <th>Skjermstatus</th>
                <th>Oppgaver</th>

            </tr>
            {% for device in devices %}
                <tr>
                    <td>{{ device.number }}</td>
                    <td>{{ device.serial }}</td>
                    <td>{{ device.model_short }}</td>
                    <td>{{ device.ip }}</td>
                    {% if device.interface or device.set_interface %}
                        <td><a href="{% url 'switchinfo:switch' name=device.interface.switch.name %}">
                            {{ device.interface.switch.name }} {{ device.interface }}</a></td>
                    {% else %}
                        <td>{{ device.port }}</td>
                    {% endif %}
                    {% if device.interface.poe_status %}
                    <td>{{ device.interface.poe_status }}
                        {% if device.interface.poe_status == 'deliveringPower' %}<a href="{% url 'device_status:power_cycle_device' device=device.serial %}">R</a>{% endif %}
                            </td>
                    {% else %}
                    <td></td>
                    {% endif %}
                    <td>{{ device.name }}</td>
                    <td>{{ device.description|default:"" }}</td>
                    <td class="{{ device.last_seen_class }}">{{ device.last_seen }}</td>
                    <td>{{ device.uptime|default:"" }}</td>
                    <td>{{ device.message|default:"" }}</td>
                    <td>{{ device.screen_status|default:"" }}</td>
                    <td>
                        <a href="{% url 'device_status:actions_pending' serial=device.serial %}">{{ device.pending_actions.count }}</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

pimanager/templates/pimanager/power_cycle.html
{% extends 'pimanager/base.html' %}

{% block content %}
    <h2>Power cycling {{ device }}</h2>
    Output:
    <pre>{{ output }}</pre>
{% endblock %}